version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
   # ports:
   #   - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./downloads:/home/seluser/Downloads
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2g'   
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./downloads:/home/seluser/Downloads
  search-module:
    image: sharanyasb/selenium-docker
    shm_size: '2g'
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - MODULE=search-module.xml
      - BROWSER=chrome
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output
  book-flight-module:
    image: sharanyasb/selenium-docker
    shm_size: '2g'
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - MODULE=book-flight-module.xml
      - BROWSER=firefox
    volumes:
      - ./output/book-flight:/usr/share/udemy/test-output